---
- name: reboot an ansible host
  hosts: all
  become: true
  tasks:
     - name: reboot the ansible host
       ansible.builtin.reboot:
         msg: "A reboot action triggered  by ansible"
         pre_reboot_delay: 20
         version: 0.0.3

